### ISSUE TITLE
Scribd.Net with Azure

### ISSUE THREAD

**Issue by flash22231** [JPaulDuncan/Scribd.Net#1]
Hi i am working on a asp project which is hosted to Windows Azure...I was using Scribd upload on localhost and it worked fine. Until when i uploaded the project into Windows Azure, it couldn't upload to Scribd. I tried all kinds of way but in vain, i couldn't  upload it into Scribd...Does Scribd api supports uploading of files with Windows Azure blob storage function?

**Comment by JPaulDuncan** [comment]
I don't know.  Can you share with me the code you're attempting to run?

**Comment by flash22231** [comment]
Erm i have solved the problem. Thanks for replying
